# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_id', '0002_user_brand_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brand_limit',
        ),
    ]
